### ISSUE TITLE
Loading Issue

### ISSUE THREAD

**Issue by benhollister** [griff/metaz#103]
I can't seem to find the answer to this here. I hadn't used MetaZ for a while (new child!) and went to add some data to a movie tonight. I had to update to the latest version], and then had the #87 Atomic Parsley issue, but with those resolved I still have a loading problem.

When I either "+" or DnD a file It just sits with the loading circle not moving. I thought it might be bandwidth, but I stopped all other services using bandwidth and left it for over an hour with no success.
I run OSX 10.9.2 on a mid 2010 Mac mini. The movie is an mp4 recently converted from an avi using iSkysoft and then added to iTunes.

Thoughts?
![screen shot 2014-04-06 at 7 06 12 pm](https://cloud.githubusercontent.com/assets/7194862/2624947/0e3e6d2a-bd6f-11e3-8655-2e335aac4565.png)

**Comment by hope22** [comment]
I'm getting the same issue, I can't load any file.

**Comment by benhollister** [comment]
I decided to delete and reinstall and am getting every file to load now except the one I had an issue with originally. I am going to re-merge the avi files and see if it works with the new download.

**Comment by griff** [comment]
@hope22 Sadly error reporting when load fails is not that informative. Could you look in the log and add it as a comment? There is a menu item to open it Help -> View Log
