### ISSUE TITLE
newline character?

### ISSUE THREAD

**Issue by yesonions** [griff/metaz#108]
is there a magical string that will insert a new line? example: I want to list some actors in the "Actor" field. I put each actor in a new line in my text editor like this:

Tom Cruise
Dustin Hoffman

I copy and paste the block of text into the field but when I write out the tags, and import into iTunes, they're listed side by side like this:

Tom Cruise Dustin Hoffman

Is there some string like maybe /n that will insert a new line?

**Comment by griff** [comment]
The Actors, Director, Producer and Screenwriter fields each use comma as a separator between individuals. So in your example you would type: Tom Cruise, Dustin Hoffman
