### ISSUE TITLE
Queue does not start

### ISSUE THREAD

**Issue by bigbilby** [griff/metaz#159]
When clicking Write all, my Files To Write get copied to the queue, but remain in the Files To Write list and the queue does not start by itself.
When I click Show Queue, the Queue comes up with the Files To Write listed in it. 
When I click Start, the first file status changes to Preparing for write, but nothing happens.

Has anyone else seen this issue?

I am using El Capitan 10.11.5. 
It was working a week ago.

**Comment by dmcourtn** [comment]
I have been having the exact same issue. And it doesn't happen on every file. 

I have an entire season of episodes that will not save. 

I have verified that both the folder and the individual files are not locked, and they have read/write permissions. 

It's just that the queue says "waiting to start" and never starts.

**Comment by bigbilby** [comment]
Hi dmcourtn,

I eventually overcame the issue. 

I think I simplified the file names, as there was superfluous text appended to the file names that somehow failed to be parsed by Meta Z.

I had to clear the queue and restart Meta Z, then add the files in again.

**Comment by dmcourtn** [comment]
Thanks so much. I'll give that a try!

**Comment by dmilton** [comment]
I found that if you try and update when no image is present this "queue does not start" problem is the result. Adding an image file (png in my test case) onto the mix resolved the problem. I also discovered that a file which already has an image present is okay. It's only one that has no current image and the update does not contain an image that makes things go sideways.

**Comment by bigbilby** [comment]
Thanks for that dmilton, good to know.
