### ISSUE TITLE
Thanks & Automatic Tagging

### ISSUE THREAD

**Issue by EpsilonAlpha** [griff/metaz#16]
Hi Guys,

thanks that you continue what MetaX has begun! Really big thanks for that!

One of the useful function of MetaX was the Tagging by Filename, cause i have a pretty good renamer and so it was (most times) pretty easy to tag files for iTunes. But there have been 3 Things i didn't like on that Function by MetaX:
1. MetaX could just read 3 Tag automatically
2. Episode ID was not available for tagging on this way
3. Even when the Show-Title has been correctly recognized, it's not been added to the field "Show" under TV Tags 

I'm sure you guys can make this better. 

Comment if you need any help for that.

Greetings

**Comment by EpsilonAlpha** [comment]
Any Response Please?

**Comment by griff** [comment]
Well I was working on this and had gotten pretty far when I found out that I had based my code on a library that is licensed under the GPL. That license is like an infectious disease and would have required me to change the license of MetaZ to it if I wanted to keep my tagging by filename code.

So I had to throw out my work and haven't gotten around to working on it again since then.

**Comment by EpsilonAlpha** [comment]
First i want to thank you for your really quick answer. And i'm sorry that you had to wipe away the work on the tagging feature.

But i'm looking forward that you can manage it to implement someday.

I use MetaZ to tag Let's Plays from YouTube and it works very well:
1. I Download the Video (it's already in MP4) 2. MetaZ (batch-)tags the Video(s) as TV-Episode (i finally managed to make presets for the 4 Series i use the most), throws it into iTunes (and from today i can report that it works also with iTunes 11) and then MetaZ exits.

There are just 2 things i have to make manually: 
1. Episode Number is always increasing so i can't make it in the preset
2. Delete the Original Video File when iTunes is finished with copy it to the Media-Folder, so i can save Disk-space.

But in the current state i have to say that MetaZ saves me a lot of Time and is a improved successor of MetaX!

Keep going Man! :-)
