### ISSUE TITLE
Not working in High Sierra?

### ISSUE THREAD

**Issue by Demonlawyer** [griff/metaz#168]
Tried to sort metadata for two movies after installing High Sierra and neither are able to import to meta z. Just get a grey circle on the left which more than half an hour later is still there and the movie is not in on the left.

**Comment by griff** [comment]
@Demonlawyer there is a beta release that works on High Sierra https://github.com/griff/metaz/releases/download/v1.0.beta-34/MetaZ-1.0.beta-34.zip
