### ISSUE TITLE
I don't know what these are.

### ISSUE THREAD

**Issue by umpa2018** [griff/metaz#180]
Not sure where to post for help.

Can anyone tell me what the blue dots and the check boxes for the files are ?

**Comment by griff** [comment]
The blue dot means the file has unsaved changes.

The checkbox is much like the other checkboxes in the interface. They represent that the corresponding field has been modified and you can undo that modification by clicking the checkbox. For files it means that the filename has been changed.

**Comment by umpa2018** [comment]
Thank you.
