### ISSUE TITLE
Unable to open previous or new files in Mac OS 10.13.4 beta 6

### ISSUE THREAD

**Issue by macmunfordgb** [griff/metaz#184]
App seems to think it is opening the file but never completes opening. There don't seem to be any presets.

**Comment by MetroWind** [comment]
I also have this issue

**Comment by jeffaco** [comment]
I'm running a non-BETA version of Mac OS/X, v10.13.3, and I'm experiencing the same problem. I launch MetaZ, I hit the "+" button, add a single file, and then nothing. I see round circle in the `files to write` list, but nothing, even after minutes of time.

Any suggestions, anyone? Is MetaZ working with recent versions of Mac OS/X (High Sierra)?

**Comment by sbliss** [comment]
Same problem. Frustrating. OSX 10.13.4

**Comment by jeffaco** [comment]
Due to lack of comment here, I ended up taking a look at [Subler](https://subler.org/). I needed to tag, and MetaZ wasn't working for me.

[Subler](https://subler.org/) seems to fit the bill, although I do prefer the UI of MetaZ.

**Comment by macmunfordgb** [comment]
Well, I tried it and it works. I wish it loaded from the database like M.z did though.

**Comment by jeffaco** [comment]
[Subler](https://subler.org/) does load from a database (at least it did for me)! What makes you say it doesn't?

I will grant you, as I said: the UI of MetaZ is WAY better. But one works right now and one does not ...

**Comment by sbliss** [comment]
**Subler** works great (despite the UI). Wasn't sure what I was going to do. Thx!

**Comment by macmunfordgb** [comment]
Well, I can’t say that I went through it real well. I will double check the database pull.

**Comment by dagronf** [comment]
Have you tried downloading the latest beta?  

https://github.com/griff/metaz/releases/download/v1.0.beta-38/MetaZ-1.0.beta-38.zip

There were a number of bugs related to high Sierra and griff has been doing an amazing job sorting them out.

See: https://github.com/griff/metaz/issues/174

**Comment by macmunfordgb** [comment]
That is much better.  It actually opens the file. Thanks!!

**Comment by dagronf** [comment]
Brilliant!

**Comment by sbliss** [comment]
Thats the fix for 10.13.4. Thx!

**Comment by griff** [comment]
I am closing this as resolved
