### ISSUE TITLE
"Wheee" dialog box on every file I add, write to

### ISSUE THREAD

**Issue by ZachRosing** [griff/metaz#187]
If I open a series of MP4 files in Beta38, every individual file pops up with a "Wheee Opened" dialogue box, and then "Wheee Item Completed" when writing. I have to manually click OK for every single file I import and write to. This behavior never happened in the past and it's incredibly annoying. Any suggestions?  I'm on High Sierra 10.13.4.

**Comment by snorbaard** [comment]
This happens when you enable the **Example Actions** option under **_When Done_**.

**Comment by griff** [comment]
I have removed the “Example Actions” plugin from the released versions since that plugin was more a demonstration of how to write your own plugins in AppleScript and so was more an annoyance to normal users than anything else.
