### ISSUE TITLE
Adding image?

### ISSUE THREAD

**Issue by khaliel** [griff/metaz#19]
Again, we can't add an image in 10a9. Drag/Drop doesn't work and there is no other button to do it.
Please, is it really complicated to add a "select" button to choose an image on the hard drive? It would solve the recurring drag/drop broken problem.

PS: This problem is known and reported by SteveBell some questions below for version 10a9. It was 6 months ago. Still no answer.

**Comment by griff** [comment]
It should be fixed with the just released 1.0a10
