### ISSUE TITLE
Issue #173 with Mojave

### ISSUE THREAD

**Issue by MC0101010** [griff/metaz#198]
Version 1.0a15 (13.11.27.14.8abfa83)
10.14 Beta (18A336e)

When using the open command as well as drag and drop of any MP4 or M4V file I get the circle in the left hand side and the items never load.  I can still do thing like look at my due but I can't load media to tag.  I will include the System Log of the events...

Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=2] -[SearchController doSearch:] Starting search 1
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/TheTVDBPlugin.mzsearchprovider'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/OSXNotificationPlugin.mzactions'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/TheMovieDb.mzsearchprovider'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Add to iTunes.scpt'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Quit MetaZ.scpt'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/GrowlPlugin.mzactions'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/AtomicParsleyPlugin.mzdataprovider'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/AlertWindowPlugin.mzactions'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/TagChimp.mzsearchprovider'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Example Actions.scpt'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Update iTunes.scpt'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.TheTVDBPlugin'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.plugin.OSXNotificationPlugin'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.TheMovieDb'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Add to iTunes'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Quit MetaZ'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.plugin.GrowlPlugin'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=1] -[MZMultiGrowlWrapper load] path: /Applications/MetaZ.app/Contents/PlugIns/GrowlPlugin.mzactions/Contents/Frameworks/Growl.framework/Versions/1.3.1
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=2] -[MZMultiGrowlWrapper load] Using Growl.framework 1.3.1 (1.3.1)
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.AtomicParsleyPlugin'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.plugin.AlertWindowPlugin'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.TagChimp'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Example Actions'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Update iTunes'
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: [lvl=1] -[SearchController finishedSearch:] Finished search 0
Jul 26 19:28:53 Miless-iMac MetaZ[7264]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
Jul 26 19:29:05 Miless-iMac MetaZ[7264]: [lvl=1] -[MZTaskOperation startOnMainThread] Launch AtomicParsley /Users/miles/Downloads/Vampyres.1974.1080p.mp4 -t

**Comment by krizleebear** [comment]
I have the same problem with the final version of OSX Mojave.

Update: A fix is already existing in the beta version, available via
`brew cask install metaz`

**Comment by scorpion7-7** [comment]
For those not running/using brew - is there a download/install version of the beta?

**Comment by randomsequence** [comment]
@scorpion7-7 under Releases: https://github.com/griff/metaz/releases

**Comment by griff** [comment]
I am closing this issue as it should be fixed.
