### ISSUE TITLE
Quick question & thanks

### ISSUE THREAD

**Issue by SteveBell** [griff/metaz#2]
Guys, thanks for releasing 1.0a9, finally! :)

Made my day. Also you are no longer on lighthouse, right? Just so I understand where to look for open issues. Or is lighthouse now private just for the devs?

**Comment by griff** [comment]
We are moving to github issues. So in the coming time we will transfer all issues from lighthouse to here and then shutdown our lighthouse account. Among other things we got tired of lighthouse not sending a mail when new issues where created.

**Comment by SteveBell** [comment]
hehe, lighthouse issue is know to me as well. I think the project I'm involved with even has a ticket at entp for that ;)
