### ISSUE TITLE
Is there going to be an archive feature?

### ISSUE THREAD

**Issue by chenrygithub** [griff/metaz#20]
One of the most useful features of MetaX for me was the archive feature. I don't see it here, is it going to be included?

**Comment by griff** [comment]
What did you use it for? I myself never used it for anything other than to apply the same tags to a different file which MetaZ supports via copy / paste. When I started MetaZ I couldn't really come up with any other good use case for the archive feature and so I didn't implement it. But if you have one I'd love to hear it and take it under consideration.

**Comment by chenrygithub** [comment]
Pretty much that mate. Almost exclusively for series, I drop in the new episode, in the archive select the previous episode, hit the toggle button, then fill in the bits that are different, date, summary etc. I didn't realise you could cut 'n paste (just tried it and it works a treat).

Thanks for the quick reply!

**Comment by fleshparade** [comment]
First off, I love MetaZ compared to MetaX, but I do believe an archive feature would be useful. Let's say you have a DVD version and then months later get a Bluray version. It would be nice to just drop in the new file and click on the archived tag without having to recreate it. I would love to see this feature added.

**Comment by griff** [comment]
@fleshparade but won't you still have the file with the DVD version in your scenario? Because then you could just open both the DVD version and Bluray version and copy the tags over.

**Comment by fleshparade** [comment]
Gotcha, if that's possible then that will work. Thanks!

René J. Perez II
