### ISSUE TITLE
"File_name.mp4 is an unsupported format"

### ISSUE THREAD

**Issue by molnizzle** [griff/metaz#204]
Not sure what to make of this. The entire reason I muted to mp4 was to get metadata tags.

**Comment by griff** [comment]
Is this when you try to load the file? What version of MetaZ are you using?

**Comment by molnizzle** [comment]
Yep, when I try to load the file. I'm using version 1.0.beta-43, just downloaded yesterday.

**Comment by griff** [comment]
I have tried to make a new version of MetaZ that should include more information in the error message. Could you try that?

**Comment by griff** [comment]
@molnizzle I am closing this issue since you never replied to my comment.
