### ISSUE TITLE
Adding numerical files imports them out of order

### ISSUE THREAD

**Issue by DarkJamie** [griff/metaz#207]
Just as the title says. Screengrab attached

![Screen Shot 2019-09-30 at 2 20 57 AM](https://user-images.githubusercontent.com/55978433/65866034-08a97b80-e329-11e9-832a-92964127bf8c.jpg)

**Comment by griff** [comment]
The files load as fast as possible and that is the order. Press the `Files To Write` header of the Files table and it should sort the files

**Comment by griff** [comment]
I will see if I can't change the code so that sorted by filename is the default.

**Comment by DarkJamie** [comment]
That would be fantastic. It's not a big deal for small sets, but reordering lists is a bit of a pain in the butt.
