### ISSUE TITLE
What is the Advanced tab all about?

### ISSUE THREAD

**Issue by slessard** [griff/metaz#21]
When updating metadata for movies (.mp4 files) I never see any options/settings in the Advanced tab. What's the purpose of this tab?

**Comment by griff** [comment]
Well the thought was that it would contain an editor for all tags not shown in any of the other tabs. I have just never gotten around to actually making it.

**Comment by slessard** [comment]
OK. Good to know I'm not doing something wrong. Thanks for the reply.

**Comment by anoncorporation** [comment]
yeah came here looking for info on this. thought maybe my download was wonky. what i liked with Metax was to remove the encoded by Handbrake blah blah blah garbage that would be on all the encodes...if you could get that up and running that be sweet.

thanks for the work on MetaZ, good alternative for MetaX!
