### ISSUE TITLE
TV Shows

### ISSUE THREAD

**Issue by Nik-Nak** [griff/metaz#212]
Right: I’m having issues using MetaZ Version 1.0.beta-49 (19.06.19.11.d5e7d11) on macOS Catalina (macOS 10.15.1 19888)

I’m having no issue adding metadata to movies: but having a lot of trouble add data to TV shows.

Basically?   I need to fill in quite a lot, manually.

What’s happening, do we know?

**Comment by griff** [comment]
It seems that TheTVDB is returning errors when hitting the API at the moment.

**Comment by griff** [comment]
It might also be that they have shut down the old version 1 API that MetaZ still uses.

**Comment by Nik-Nak** [comment]
> It might also be that they have shut down the old version 1 API that MetaZ still uses.

Hmmm … 

Can we do anything at our end?

Please bear in mind, I am no coder: so any solution would need to be east for a layman to use …

**Comment by griff** [comment]
It was just temporary downtime and the service looks to up again from where I am.

For the API version update it is something that I need to fix by rewriting that part of the code.

**Comment by Nik-Nak** [comment]
OK, looks like it’s back up at my end: Cheers, Griff …
