### ISSUE TITLE
How do I use this software?

### ISSUE THREAD

**Issue by tsuliwaensis** [griff/metaz#213]
I add a file, but nothing ever returns from the search. I think it's running a search. There's no indicator that anything is happening at all. I've tried very common shows like The Office and Friends and it does not do anything at all.  I have the plugins for The TV DB and The Movie DB enabled.

**Comment by evansharp** [comment]
A simple how-to for the search feature would be very welcome!

**Comment by griff** [comment]
When searching for a Movie it will use the search field above the search result table and fill out that field with the `Title`. But when searching for a TV episode it instead uses the `Show`, `Season` and `Episode` fields in the `Video` tab. If only `Show` and `Season` are filled out it returns data for all episodes in the season but at least these two fields need to be filled out for TV search to work.
