### ISSUE TITLE
Cannot get artwork for TV Shows.

### ISSUE THREAD

**Issue by ComputerGuyMike** [griff/metaz#216]
Since around November 15th, I have been unable to get artwork for TV Shows.  Movies work fine.  All of the rest of the Metadata is fine.  I have tried this on two different Macs and both have the same issue.  Running Version 1.0.beta-49.

**Comment by dagronf** [comment]
Same issue here. 

I had a wander through in the debugger, it _appears_ that the theTVDB has changed the meanings of the fields returned for the `fetchSeriesBannersCompleted` call.

It appears that `BannerType2` in the xml response now returns the size of the banner as a string (eg. "600x1000") whereas previously it would appear to have been a banner type (the code looks for "season").  I commented out the check and the banners now appear, however it appears that there are some other minor changes to the api as well.  Need to track down what other changes have been made to the API before jumping to a solution.

**Comment by dagronf** [comment]
Found this in the forums :-

> Per Subject line is this query still functional? Worked nice prior to v3 rollout but now there's much data missing in the response

https://forums.thetvdb.com/viewtopic.php?t=60747

**Comment by griff** [comment]
I have some good news. When #229 is released this is no longer a problem.

**Comment by griff** [comment]
This is now fixed and released so I will leave this open for a week for any comments or problems with the fix and then I am going to close it.
