### ISSUE TITLE
Quick UI question

### ISSUE THREAD

**Issue by slessard** [griff/metaz#22]
There's a few things in the MetaZ GUI that I don't understand. 
1:  In the Search pane what is the purpose of the checkbox in the "C" column?
2:  In the Files pane what is the purpose of the "dot" column?
3:  Also in the Files pane what is the purpose of the unlabeled column of checkboxes?

**Comment by griff** [comment]
The C column is an indicator that the search result has chapters (only TagChimp results have this). A check means it has both chapter names and times while a - means it only has chapter names.

The a dot in the dot column indicates unsaved changes.

Like all fields have a checkbox that shows if that field has been edited and that you can uncheck to discard the changes, so does the files pane have a checkbox column that serves the same function for file name changes

**Comment by slessard** [comment]
Now I can use MetaZ a little more efficiently. Thanks a bunch!
