### ISSUE TITLE
Growl code sign fails

### ISSUE THREAD

**Issue by jmcintyre** [griff/metaz#220]
I haven't been able to get the Growl plugin to successfully code sign in Xcode 11.

```
CodeSign /path/metaz/build/Debug/GrowlPlugin.mzactions (in target 'GrowlPlugin' from project 'MetaZ')
    cd /path/metaz
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --timestamp=none /path/metaz/build/Debug/GrowlPlugin.mzactions

/path/metaz/build/Debug/GrowlPlugin.mzactions: bundle format unrecognized, invalid, or unsuitable
In subcomponent: /path/metaz/build/Debug/GrowlPlugin.mzactions/Contents/Frameworks/Growl.framework
Command CodeSign failed with a nonzero exit code
```

I have temporarily removed the plugin from the local, but I'm trying to find a real solution.

**Comment by jmcintyre** [comment]
The problem appears to be a failure to sign because the old growl framework isn't in the proper framework format. I considered looking at this to try to get it to work, but I guess the question is

Is growl support important? If not, should it be replaced with explicit support for notification center? If it remains important, should we go ahead and upgrade to 2.0.1 which appears to be delivered with a proper framework? Keep in mind that Growl hasn't been updated since 2012. I'm happy to take a look at either path.

**Comment by griff** [comment]
No growl is no longer important. I believe it already detects and uses notification center if avalable.

**Comment by jmcintyre** [comment]
I found a way to get Growl to sign by reorganizing it. I have one branch that does that:

https://github.com/jmcintyre/metaz/tree/configure_growl_to_be_codesignable

and another that removes it entirely:

https://github.com/jmcintyre/metaz/tree/remove_growl

I can see arguments for both. Let me know which you'd like me to put a pull request in for.

**Comment by jmcintyre** [comment]
I've gone ahead and created a pull request for each of the concepts. Please take a look at them and see which of the two will work for you (only one should be done accepted at most).

https://github.com/griff/metaz/pull/222
https://github.com/griff/metaz/pull/223

**Comment by jmcintyre** [comment]
Fixed by the remove growl checkin.
