### ISSUE TITLE
MetaZ not fetching metadata for BBC Documentaries

### ISSUE THREAD

**Issue by AveryTimm** [griff/metaz#225]
Perhaps because there are so many seasons and episodes, MetaZ is no retrieving info for episodes from the series "BBC Documentaries". I think this happened to me with another show that had many seasons and episodes, but I can't remember which one that was...

https://www.thetvdb.com/series/bbc-documentaries/seasons/official/2019

Other shows are working, while this one isn't.

I often have to look up shows on the thetvdb website to find the episode number, so I already have the URL handy... if new features are ever added, how about this one... in the  search field in the right pane, in the pull down menu for search terms...add an option for URL. If a valid URL is pasted is (https://www.thetvdb.com/series/bbc-documentaries/episodes/7491338 for example), it would pull the info from that page.

**Comment by griff** [comment]
Is this still a problem with the latest MetaZ version? I have tested a little and when specifying both show name and year as season it seems to work.

**Comment by AveryTimm** [comment]
It seems to work now - Version 1.0.beta-113 (20.03.17.11.8e86c75). Thanks.
