### ISSUE TITLE
beta 74 crash on launch - libswiftAppKit.dylib not found

### ISSUE THREAD

**Issue by wademaxfield** [griff/metaz#230]
Launching the new beta 74 crashes on OS X 10.13.6 and 10.14.6 with an EXC_CRASH

Process:               MetaZ [24264]
Path:                  /Applications/MetaZ.app/Contents/MacOS/MetaZ
Identifier:            org.maven-group.MetaZ
Version:               1.0.beta-74 (20.03.08.21.b9ec864)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           MetaZ [24264]
User ID:               501

Date/Time:             2020-03-09 10:34:04.533 +1300
OS Version:            Mac OS X 10.13.6 (17G11023)
Report Version:        12
Anonymous UUID:        F91C5575-CAB3-DAFC-1CF5-78C0201E57A4

Sleep/Wake UUID:       6FF6AD85-A711-4A93-88CA-F1C354B417DE

Time Awake Since Boot: 250000 seconds
Time Since Wake:       3300 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /Applications/MetaZ.app/Contents/Frameworks/MetaZKit.framework/Versions/A/MetaZKit
  Reason: image not found

Binary Images:
       0x10d2e1000 -        0x10d31bff7 +org.maven-group.MetaZ (1.0.beta-74 - 20.03.08.21.b9ec864) <2A63F00B-7CDF-335C-80C3-EBA285DB7535> /Applications/MetaZ.app/Contents/MacOS/MetaZ
       0x10d372000 -        0x10d3beff7 +org.maven-group.MetaZKit (1.0.beta-74 - 20.03.08.21) <69D9FB1C-EC1F-38E0-A810-CAC1BAEAF672> /Applications/MetaZ.app/Contents/Frameworks/MetaZKit.framework/Versions/A/MetaZKit
       0x10d40e000 -        0x10d457ff7 +org.sparkle-project.Sparkle (1.19.0 - 1.19.0) <F82900CD-E515-3377-9E1B-F90A6EFA304A> /Applications/MetaZ.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x10f7d2000 -        0x10f81cadf  dyld (551.5) <ACC6AC7F-EAD9-340E-B2A8-AD26FE5B387B> /usr/lib/dyld
    0x7fff53ce1000 -     0x7fff54b3ffff  com.apple.AppKit (6.9 - 1561.61.100) <E4074E39-9A3D-3EFF-9384-DDA7C9666E29> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff5568f000 -     0x7fff55a2cfff  com.apple.CFNetwork (902.5 - 902.5) <2D37E75A-42FD-3CDE-BAE3-D4228EF813F0> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff55f53000 -     0x7fff55f53fff  com.apple.Cocoa (6.11 - 22) <17A98C08-64CF-3232-80EE-E10BAF68778F> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff56714000 -     0x7fff56bb0fff  com.apple.CoreFoundation (6.9 - 1455.12) <D8DF93F5-4558-3B28-8BDF-9739C995D27C> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff56bb2000 -     0x7fff571e1ff7  com.apple.CoreGraphics (2.0 - 1161.21.3) <1DEF1BEB-08A3-35DA-8372-5C2D8C886EC0> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff578a7000 -     0x7fff578a7fff  com.apple.CoreServices (822.37 - 822.37) <7B04988B-C0D4-314E-8B3B-AE446B4A38CD> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff58890000 -     0x7fff58c57ffb  com.apple.Foundation (6.9 - 1455.12) <3B5567E0-775C-36D2-8052-DA42CA319EEA> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff61b1d000 -     0x7fff61b1dfff  com.apple.quartzframework (1.5 - 21) <DCEB0FCC-2C32-3D02-8752-7B6FA009AB85> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff62d35000 -     0x7fff62da5ff3  com.apple.SystemConfiguration (1.17 - 1.17) <CD4A4C66-7886-3323-A3B9-0C8952500856> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff7c42a000 -     0x7fff7c42bffb  libSystem.B.dylib (1252.50.4) <97EECA63-F728-3F2E-87F3-6DD60DEF17AB> /usr/lib/libSystem.B.dylib
    0x7fff7d11a000 -     0x7fff7d20bff7  libiconv.2.dylib (51.50.1) <2FEC9707-3FAF-3828-A50D-8605086D060F> /usr/lib/libiconv.2.dylib
    0x7fff7db65000 -     0x7fff7df563b7  libobjc.A.dylib (723) <BEEA51E2-1C4D-3672-87F6-F267B4AC6221> /usr/lib/libobjc.A.dylib
    0x7fff7e57c000 -     0x7fff7e58effb  libz.1.dylib (70) <48C67CFC-940D-3857-8DAD-857774605352> /usr/lib/libz.1.dylib

**Comment by griff** [comment]
Crap that was bad. I should be fixed now.

**Comment by wademaxfield** [comment]
Beta 80 opens fine.  8)
