### ISSUE TITLE
Dark mode on Catalina doesn't display correctly

### ISSUE THREAD

**Issue by blake-bauman** [griff/metaz#232]
The Files list view and the Short/Long descriptions don't display correctly when using Dark Mode on Catalina.

The files list view alternates between a dark and light background which looks odd.  The rows with the dark background look fine, but the rows with the light background don't show the white text unless you select the item in that row.

The short and long description text boxes are dark background with black text.

**Comment by blake-bauman** [comment]
This is with Beta 80.

**Comment by matthew-cox** [comment]
Can confirm the same display issues exist with Dark Mode on Mojave.

**Comment by bdbaddog** [comment]
I'm seeing this same with Beta 79 which I just installed because I was prompted for update..

**Comment by griff** [comment]
I have released a version that fixes all the issues with dark mode I could find. That includes the issues mentioned here and one issue with label color in the queue.

**Comment by blake-bauman** [comment]
I downloaded 91 and the Files list seems to be ok, but the Long/Short description boxes still seem to have the issue.  The text I'm typing in is black on the black background.

is there a way for me to upload a screenshot?

(Using Catalina 10.15.3)

**Comment by griff** [comment]
@blake-bauman at the bottom of the the comment box for issues here you can click or drop images into to attach them. But it shouldn't be necessary since I have just released version Beta-94 that has fixes for the issue you describe.

**Comment by blake-bauman** [comment]
Confirmed.  Thanks!
