### ISSUE TITLE
JPEG-Images set by MetaZ as Preview Image will not be taken by Nextcloud Preview App

### ISSUE THREAD

**Issue by britzke** [griff/metaz#251]
JPEG-Images that are set by MetaZ as preview image will not be recognised by [Nextcloud Preview App](https://github.com/rullzer/previewgenerator). This may not be an issue for MetaZ but may be for the Nextcloud Preview App. I made this issue here with the hope of triggering some information flow into that project.
So I made a similar [issue for that project](https://github.com/rullzer/previewgenerator/issues/214) which I linked to this issue.

**Comment by britzke** [comment]
If someone would point me a link (may be to some source code location, I already searched for it without luck), I would gather further information to  push it into  the Nextcloud Preview App project.

**Comment by griff** [comment]
Have you tried setting the preview image with other tools like [Subler](https://bitbucket.org/galad87/subler/wiki/Home)?

**Comment by griff** [comment]
And by preview image I assume you mean the posters/artwork that MetaZ adds.

**Comment by britzke** [comment]
Sorry for the late reply and...
yes, I now tried it with Subler. Here it is the same the preview images are not shown in Nextcloud, and...
yes, by preview image I mean the poster/artwork that MetaZ adds.

**Comment by griff** [comment]
I looked at Nextcloud and it seems to generate movie previews [here](https://github.com/nextcloud/server/blob/d73b378c224de8d6f5e8e61a10e90b4ed2787b23/lib/private/Preview/Movie.php) so your best bet is to convince Nextcloud that they should look at movie metadata or that they make a different preview provider that loads metadata.

There isn't much more I can do so I am going to close the issue.
