### ISSUE TITLE
Ability to create new chapters?

### ISSUE THREAD

**Issue by iancbogue** [griff/metaz#255]
I'm brand new to the app, so I may be missing something, but I can't find a way to add chapters to my MP4 files. I can rename existing chapters just fine. Is this not a feature included in the app? If not, I think it would be an excellent addition if it's something that's possible to add.

**Comment by griff** [comment]
Well you actually can create new chapters I just never got around to making a UI for it.
The chapters table supports copy/paste of text with chapters in different formats.

There is the MP4v2 format:
```
00:00:00.000  Chapter 01
00:00:05.000  Chapter 02
00:00:10.000  Chapter 03
```

The format used by some web sites which uses chapter duration:
```
1. Chapter 01 [00:05]
2. Chapter 02 [00:05]
3. Chapter 03 [60:00]
```

And then there is the Ogg format:

```
CHAPTER00=00:00:00.000
CHAPTER00NAME=Chapter 01
CHAPTER01=00:00:05.000
CHAPTER01NAME=Chapter 02
CHAPTER02=00:00:10.000
CHAPTER02NAME=Chapter 03
```

**Comment by iancbogue** [comment]
Oh okay. That's awesome, thank you so much!
