### ISSUE TITLE
Cannot get MetaZ to perform TV show searches

### ISSUE THREAD

**Issue by tonemcd** [griff/metaz#257]
### Issue

Can't get MetaZ to perform TV show searches.

Any ideas as to what I can try?

### Background

I have encoded some TV shows using Handbrake 1.4.1 in .mp4 format. I drag and drop them onto MetaZ (prompt for video type is set) and the name of the file is dropped in the search field. Nothing other than the file name appears in the search results. I can change the content of the search field and still 

The drop down search menu has the following settings
Title - enabled
TV Show - NOT enabled
Season - NOT enabled
Episode - NOT enabled
Chapters - enabled

If I change the type to Movie, then I do get some matches. I dropped the same file into Meta Z twice, once as a TV show and once as a Movie and as a movie, some matches are found, nothing with the TV show.

I looked at the Little Snitch network monitor to see what was going on. A Movie search created some network activity, but "TV Show" didn't. I went through all the 'Video Type' options from Home Movie to iTunes U and the only one that created network activity was Movie.

For completeness, I cloned the repo and built MetaZ from source, built the app and and tried to figure out what was going on. I got the same behaviour. I've written a few small apps in Obj-C for my own benefit and some other Swift iOS apps, again for myself, so I can just about use the debugger and breakpoints, but it was a bit beyond me.

Any pointers would be very welcome.

### Settings

Presets - None
Enable auto search - set
Show ratings from - UK, AU, NZ
Update TV App - set
Alert Window - set
Show MacOS notifications - set
The Movie DB - set
Atomic Parsley - set
Quit MetaZ - NOT set
TheTVDB - set
The Movie DB Next Gen - set
Add to TV app - NOT set
TheTVDB 3 - set

### Versions used

MetaZ version 1.0.beta-116 downloaded from GitHub releases
MetaZ cloned from GitHub and built with Xcode 13.0
Big Sur 11.6
Handbrake 1.4.1
Xcode 13.0
Little Snitch 5.3

**Comment by griff** [comment]
The problem is most likely the dropdown in the search field. The enabled/disabled status there determines what is used for searching. And for TV search you need at least “TV Show” and “Season” to be enabled. If you can’t enable them by clicking on them it means that you haven’t filled out those fields for the file. So go to the “Video” tab and fill out at least those two fields.

**Comment by tonemcd** [comment]
Apologies for the late reply, I was away from my machine.

Thanks heaps! I did what you suggested, filling in the "TV Show" and "Season" field in the "Video" tab and both those fields are enabled and the search ran just fine.

Happily closing this issue!
