### ISSUE TITLE
1.0.2 constant beach-balling on macOS Catalina

### ISSUE THREAD

**Issue by DigiH** [griff/metaz#262]
Just downlaoded version 1.0.2 on macOS Catalina 10.15.7 (19H1824)

Whenever a field/popup focus is changed, there is a few second beach ball, making it virtually impossible to use this version on Catalina. Also impossible to quit (either through menu, dock menu or cmd-Q) 1.0.2, only able to force quit.

Couldn't find any notes if this version requires macOS later than 10.15, but need to go back to 1.0.1 for the time being.

Happy to help if further info is needed for these issues on Catalina.

**Comment by dagronf** [comment]
I was able to reproduce the issue with 1.0.2 on Catalina. Unfortunately it relates to one of the changes I made recently to attempt to improve performance. While this works on 11 and above, it appears Catalina works slightly differently.

I've pushed up a fix which I've tested on locally on Catalina and appears to resolve the issue.

Many apologies for the inconvenience.

**Comment by dagronf** [comment]
This fix hopefully will go into 1.0.3 (waiting on review)

**Comment by DigiH** [comment]
Thanks a lot @dagronf for addressing this so quickly.

Looking forward to a future release, but happily working here with 1.0.1 in the meantime.

I very much appreciate this software project!

**Comment by griff** [comment]
Now there is a version 1.0.3

**Comment by DigiH** [comment]
WOW, thanks a lot for the very fast update! :)

Verified with 1.0.3 as fixed. Closing.
