### ISSUE TITLE
Opening movie returns AtomicParsley code 2

### ISSUE THREAD

**Issue by andyrings** [griff/metaz#272]
"Failed to process file 'Star Wars VHS Widescreen 03-08-23.mov'. AtomicParsley failed with exit code 2"

I'd be glad to send the file itself to someone to see what's going on. Nothing out of the ordinary, a file created with HandBrake on MacOS Ventura. Never ran into this before.

**Comment by dagronf** [comment]
A quick look through the AtomicParsley code shows the following two cases where it can fail with error 2

1.  "AtomicParsley error: unsupported MPEG-4 file brand found '%s'\n",
2. "AtomicParsley error: Quicktime movie files are not supported.\n");

Both of these cases seem to indicate that the movie file type isn't supported.  I noticed that the file you've put into the issue has the extension .mov (which is a quicktime movie file)... 

Could you try re-encoding the file (using Handbrake) to an mp4 format instead and see if it works in MetaZ?

**Comment by andyrings** [comment]
Yeah, that was the problem. I accidentally grabbed a .mov version of the video file and not the .mp4 version.

All is well.

----
Andy Ringsmuth
5609 Harding Drive
Lincoln, NE 68521-5831
(402) 202-1230
***@***.***
