### ISSUE TITLE
Not adding files to TV app

### ISSUE THREAD

**Issue by LDMartin1959** [griff/metaz#278]
I've got the MetaZ preferences set correctly (never really change them) but lately I've noticed a tendency for MetaZ not to add processed files to the MacOS TV app. More confounding is the fact that it is inconsistent—sometimes it adds the files just fine, other times not at all, other times, some of them. I'm attaching a log file for anyone who might find it useful.

[MetaZ.log](https://github.com/user-attachments/files/17691954/MetaZ.log)

**Comment by dmcourtn** [comment]
I'm experiencing the exact same thing. I tried adding 52 episodes like I usually do, and MetaZ hangs on the third one and doesn't proceed.
