### ISSUE TITLE
secrets.SITE_TOKEN outdated

### ISSUE THREAD

**Issue by jmcintyre** [griff/metaz#281]
@griff , the secrets.SITE_TOKEN needs to be updated for the builds to succeed through the release process. Other than this, the build process should work again with changes I checked in.

Here is the specific failure:
https://github.com/griff/metaz/actions/runs/11883146169/job/33109502342

**Comment by griff** [comment]
I am looking into it

**Comment by griff** [comment]
I think it is fixed now
