### ISSUE TITLE
libz.1.dylib not found on Silicon Mac

### ISSUE THREAD

**Issue by loshlee** [griff/metaz#283]
Beta 1.0 number 551 throws error for any file I've thrown at it so far:

Failed to process file 'file.mp4'. dyld[8438]: Library not loaded: /opt/local/lib/libz.1.dylib
Referenced from: <81238E7D-DE9C-328A-89E7-DCB2DC04CB07> ~/Library/Favorites/Movie/Plug-in/MetaZ.app/Contents/PlugIns/AtomicParsley.mzdataprovider/Contents/Resources/AtomicParsley
Reason: tried: '/opt/local/lib/libz.1.dylib' (fat file, but missing compatible architecture (have 'x86_64,i386', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libz.1.dylib' (no such file), '/opt/local/lib/libz.1.dylib' (fat file, but missing compatible architecture (have 'x86_64,i386', need 'arm64e' or 'arm64'))

I found many files so named on my system, so I copied one of them to "/opt/local/lib", which didn't exist until I created it. Maybe something else is wrong, maybe I haven't found a compatible version of the file.

**Comment by jmcintyre** [comment]
On it.

**Comment by loshlee** [comment]
Thanks.
