### ISSUE TITLE
Add option to "check all"

### ISSUE THREAD

**Issue by stonematt** [griff/metaz#30]
one of the features from MetaX that I liked was a menu bar option to "toggle" all check boxes  I haven't found a similar easy way to indicate that I wan to write all of the meta data elements that are in view - especially when I'm working on a new file that has no meta data to start with. 

If MetaZ has such an option, where is it?  Otherwise it would be nice to have a 1-click option to turn all of them one.

**Comment by griff** [comment]
It can't see what that would help with. When you edit the tags from the text fields the checkboxes get toggled when done. The only time this might get relevant is when dealing with search results or presets and they can already do something like that. I call it apply result / preset. There are several ways of doing that operation:
- In the main menu Edit -> Search -> Apply Result
- Right clicking a search result and selecting Apply Result in that menu
- Double-clicking the search result / preset
- Using the keyboard shortcut Cmd-Shift-A to apply the currently selected preset or search result

What it does is take all values from that result / preset and if the selected files don't have a value set / toggled for a given tag it sets it to the value from the result.
