### ISSUE TITLE
should I be able to add an image?

### ISSUE THREAD

**Issue by SteveBell** [griff/metaz#5]
In 1.0a8 I was able to drag and drop an image to the according fiel in MetaZ. No longer so in 1.0a9. Am I missing something or "holding it wrong"? Hm, made a nice mockup but GitHub issue system does not allow images :(

**Comment by griff** [comment]
You are not holding it wrong but a bug sneaked in and made it difficult. See issue #4

You can add an image if you have an url for it. I.e. uploaded it somewhere else.

**Comment by SteveBell** [comment]
ugh. that's ugly. will do. when is 1.0a10 coming? as always, your work is appreciated ;)

duplicate sry for not checking. closing.

**Comment by SteveBell** [comment]
But honestly I don't have a clue how to add an image via url.

**Comment by griff** [comment]
Sorry the image url comment was about images in github issues.

**Comment by khaliel** [comment]
The issue is back in a9. We, again, can't add an image!
