### ISSUE TITLE
Suggestion: Copy Tags

### ISSUE THREAD

**Issue by posaune** [griff/metaz#61]
One enhancement I'd find useful is to be able to copy all tags from one file to another.

eg: I ripped the same "title" twice from a DVD by mistake to two separate files (part 1 and part 2) and applied all the tags. When I discovered the error, I needed to re-rip part 2 but copy all the tags manually.

Or, when ripping a multi-part serial, it would be great to start applying tags to the first episode as it comes out of handbrake and then copy these to the subsequent parts as they are produced.

Thanks!

**Comment by griff** [comment]
That should already be implemented as normal copy / paste for the files list. If you select a file in the list and do a normal ⌘-C (or Copy from Edit menu) and then select a different file in the list and do ⌘-P (or Paste from Edit menu) all tags should be copied over.

Your second use-case sounds more like what Presets are designed for. Copy / Paste copies all tags from one file to another while with presets you can when creating the preset control which tags it includes and will apply.

**Comment by posaune** [comment]
The copy / paste on the file list seems to copy only the picture, genre, type, director, producer, and sorting/show - leaving quite a few other bits still to copy (as per first case scenario where a full duplicate of tags is desireable).

Presets, however, do seem able to copy everything ... so I shall use them.

Thanks!
