### ISSUE TITLE
Search Results Only Include TagChimp

### ISSUE THREAD

**Issue by jleishman** [griff/metaz#74]
Within the past few days (maybe a week at the outside) MetaZ 1.0a13 (12.12.04.06.20c53b9) has suddenly stopped retrieving search results from anywhere but TagChimp.

Prior to this, at least one other data source was included. The "Src" column showed a green stylized letter "Q", as I recall.

**Comment by griff** [comment]
I just looked into this and it seems that the version of the [The Movie Database](http://www.themoviedb.org/) API we were using was shut down permanently on September 15. because they want all people to use the newer version.

**Comment by SydSnot** [comment]
Hi

Excellent app.  Can't believe I didn't come across it earlier!

Will MetaZ be able to switch to the newer API for The Movie DB?  The stuff that came form the Movie DB seemed better organised than TagChimp, better art etc

**Comment by antelopeslr5000** [comment]
Totally agree, the Movie DB is far better organised than TagChimp. Hopefully there is a MetaZ update coming soon or at least a plug-in that will work with the new API. 

I've looked for other meta data editors for the Mac but this for me is the best by far. Thanks Griff for your hard work (with little reward!) in making MetaZ the great program that it is today.

**Comment by notlimahrelyt** [comment]
Any word on a resolution for this?

**Comment by ShadowRadiance** [comment]
I'm working on a fix for this - under Xcode 5 and ML so my branch has related changes, and some updates to google-toolbox-for-mac. Hopefully will have a usable branch in a day or two.

**Comment by griff** [comment]
@ShadowRadiance if you feel like doing the extra work of making your fix compile against the 10.5 SDK and submitting a pull request I will make a release that includes it. And as per the just instated policy you get commit rights for an accepted pull request.

**Comment by ghost** [comment]
griff, thank you for your great work on MetaZ! it is a very useful tool. therefore it is quite sad that it is impossible to use MetaZ since the search issue has occurred recently cutting it off from several databases. Have you found a solution and can you compile a new dmg / app file for mac for the new version, please?

**Comment by kungfoochris** [comment]
Has this update been complete and pulled back into the main release?  Really looking forward to having this resolved.

**Comment by ShadowRadiance** [comment]
No, sorry. The changes I was making were only working on ML... and at that it was REALLY slow talking to the new API (especially the image loading).

I'm trying to fix that but have been super busy at work the last little while.
