### ISSUE TITLE
Chapter Titles Are Not Unescaped

### ISSUE THREAD

**Issue by jleishman** [griff/metaz#86]
For example, things like "&amp;amp;" and "&amp;lt;" will still be present.

**Comment by griff** [comment]
What movie / TV show did you experience this with? It makes it easier for me to fix the issue when I can reproduce it locally.

**Comment by jleishman** [comment]
I noticed it with one of the search results for "Ultraviolet".

**Comment by griff** [comment]
I looked into this and at least for Ultraviolet the problem is that tagChimp returns some bad data (which they tend to do a lot). What I get from tagChimp is this: &amp;amp;amp; which is correctly unescaped as &amp;amp;

**Comment by jleishman** [comment]
I understand. I'll see if I can find somewhere to let tagChimp know that the problem may be on their end.
