### ISSUE TITLE
Adding files: problem

### ISSUE THREAD

**Issue by jdmssmkr** [griff/metaz#87]
I have updated to the latest version (1.0a14) and cannot open any movie file anymore, even files that I have edited with metaz in the past.

Any ideas?

**Comment by griff** [comment]
Does MetaZ crash or does it say "Unrecognized file"?

**Comment by jdmssmkr** [comment]
No crash, no message. Everything except directories is greyed-out in the open dialog.

**Comment by griff** [comment]
What version of OS X are you using? And can you drag-n-drop files to the application icon?

**Comment by jdmssmkr** [comment]
10.9, up to date. DnD doen't work.

**Comment by griff** [comment]
When you DnD'd did you get the Unsupported message? Can I get you to look in the log (Help -> View log)? Because it sounds like the atomicparsley plugin isn't loading.

**Comment by griff** [comment]
Unsupported should be Unrecognized in the above comment

**Comment by griff** [comment]
I am just remembering something that has been reported from time to time where for reasons I can't explain the atomicparsley plugin will get disabled. If that is what has happened to you you can enable it again in the preferences.

**Comment by jdmssmkr** [comment]
The atomicparsley plugin was enabled so I disabled en re-enabled the plugin again: now it works. Also, I checked the log: no error information whatsoever.

It works, I'm happy. Thank you for the tip!
