### ISSUE TITLE
Forgive my ignorance: how to INSTALL this program to begin with??

### ISSUE THREAD

**Issue by mcwwcm** [griff/metaz#93]
Sorry for my ignorance here, but I have discovered a major flaw here: MetaZ sounds great--so, uh, exactly WHAT is it, and HOW do you install it?  The instructions on this are pretty vague and lacking (and talks about a classic "moo" and I don't know what that means).  There is no installer in the package that I can see.  Is this a plugin for MetaZ?  A plugin for something else?  Is it a program?  What exactly is this and now that I've downloaded this set of files, how do I install this "program?"  I think we missed this basic instruction somewhere =)  Thanks for any help.

**Comment by Frizlab** [comment]
What you have here is the _source code_ to the Mac OS X application `MetaZ`, which is based on `MetaX`. Downloading these files won't be of any use to you if you don't have Xcode, nor know how to use it.

I am not aware of any _compiled_ version of `MetaZ` available to download (a _source code_ is compiled to create an _application_). There might be one available somewhere however.

**Comment by cflex007** [comment]
"Major flaw" . . . LMAO

The real mystery here is how you came to be on this website in the first place. :)

**Comment by mcwwcm** [comment]
oh Jesus source codes, okay I get it--sorry guys!  Thanks for the help.  I'm frustrated that MetaZ sounds like the best option on the whole entire internet for what it does, but it's not quite a consumer-friendly application yet for people like me.  I will have to research xcode.  Thanks again.

**Comment by cflex007** [comment]
mcwwcm I think what you're looking for is something like this:
https://www.dropbox.com/s/vtbh7oyufbd204b/MetaZ-1.0a13.zip

**Comment by mcwwcm** [comment]
thanks cflex!  I'll get to researching source codes.

**Comment by cflex007** [comment]
Here is the latest: https://github.com/griff/metaz/releases/download/v1.0a15/MetaZ-1.0a15.zip

**Comment by griff** [comment]
@mcwwcm well this is not actually the homepage of MetaZ. That can be found at http://griff.github.io/metaz and I keep a link to the latest compiled version of MetaZ pretty prominent there.

This page is more a for tracking the progress of the project, reporting issues and getting some support and to give people access to the source code so they can make their own versions or help out.

If you want access the the full history of compiled versions with release notes that is also stored here under the releases tab: http://github.com/griff/metaz/releases
